In [4]:
import numpy as np
rnd = np.random.default_rng()
a = rnd.integers(-10,10,(10,10))
print(a)

[[  9   9  -5   1   5   5   7  -4  -8   7]
 [  6   2  -1   5   2  -9   9   2  -6   6]
 [  3  -8   7  -1   9  -3  -6  -5  -8  -7]
 [ -9 -10  -5   1  -5   4   0   1  -4  -4]
 [  5  -4  -1   8  -9   4   0   1   5  -3]
 [ -4  -6  -7   3 -10   7   5   9   9   7]
 [ -3   0   6   2  -9 -10  -8  -3  -9  -4]
 [ -6  -7   9   9  -1   0  -1   2   1   4]
 [  4  -5  -2  -7  -7   8  -9   2 -10   0]
 [ -8  -5   5   4   6  -2   6  -8  -9   2]]


# Нормализация

In [5]:
normalize = a / np.linalg.norm(a)
print(normalize)

[[ 0.15122313  0.15122313 -0.08401285  0.01680257  0.08401285  0.08401285
   0.11761799 -0.06721028 -0.13442056  0.11761799]
 [ 0.10081542  0.03360514 -0.01680257  0.08401285  0.03360514 -0.15122313
   0.15122313  0.03360514 -0.10081542  0.10081542]
 [ 0.05040771 -0.13442056  0.11761799 -0.01680257  0.15122313 -0.05040771
  -0.10081542 -0.08401285 -0.13442056 -0.11761799]
 [-0.15122313 -0.1680257  -0.08401285  0.01680257 -0.08401285  0.06721028
   0.          0.01680257 -0.06721028 -0.06721028]
 [ 0.08401285 -0.06721028 -0.01680257  0.13442056 -0.15122313  0.06721028
   0.          0.01680257  0.08401285 -0.05040771]
 [-0.06721028 -0.10081542 -0.11761799  0.05040771 -0.1680257   0.11761799
   0.08401285  0.15122313  0.15122313  0.11761799]
 [-0.05040771  0.          0.10081542  0.03360514 -0.15122313 -0.1680257
  -0.13442056 -0.05040771 -0.15122313 -0.06721028]
 [-0.10081542 -0.11761799  0.15122313  0.15122313 -0.01680257  0.
  -0.01680257  0.03360514  0.01680257  0.06721028]
 [ 0.0672